parameters:
  pool: ''

jobs:
- job: Wasm_UITests
  container: nv-bionic-wasm

  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - checkout: self
    clean: true

  - bash: |
      sudo apt install ruby
      gem install github_changelog_generator -v 1.14.3
      export CHANGELOG_GITHUB_TOKEN="$(CHANGELOG_GEN_PAT)"
      github_changelog_generator nventive/uno --output $(build.artifactstagingdirectory)/changelog.md

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: NugetPackages
      ArtifactType: Container
