parameters:
  pool: ''

jobs:

- job: Wasm_UITests_Compare
  dependsOn: Wasm_UITests_Snap

  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - checkout: self
    clean: true

  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: 4.9.1
      checkLatest: false

  - task: MSBuild@1
    inputs:
      solution: src/Uno.UI.TestComparer/Uno.UI.TestComparer.csproj
      msbuildLocationMethod: version
      msbuildVersion: latest
      msbuildArchitecture: x86
      msbuildArguments: /r "/p:Configuration=Release"
      clean: false
      maximumCpuCount: true
      restoreNugetPackages: false
      logProjectEvents: false
      createLogFile: false

  - script: |
     src\Uno.UI.TestComparer\bin\Release\net461\Uno.UI.TestComparer.exe "azdo" --pat="$(UITestsCompare_PAT)" --base-path="$(build.artifactstagingdirectory)" --source-branch="%GIT_SOURCEBRANCH%" --target-branch="%GIT_TARGETBRANCH%" --artifact-name="uitests-results" --artifact-inner-path="uitests-results\screenshots" --definition-name="$(Build.DefinitionName)" --project-name="$(System.TeamProject)" --server-uri="$(System.TeamFoundationCollectionUri)" --current-build="6340" --run-limit="3"

    env:
      GIT_TARGETBRANCH: "$(System.PullRequest.TargetBranch)"
      GIT_SOURCEBRANCH: "$(Build.SourceBranch)"
    displayName: 'Compare UI Tests screenshots'


  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: '$(build.artifactstagingdirectory)\*.xml'
      testRunTitle: 'Screenshots Compare Test Run'
      testResultsFormat: 'NUnit'
      failTaskOnFailedTests: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)
      ArtifactName: wasm-uitests-compare-results
      ArtifactType: Container
